apiVersion: appprotect.f5.com/v1beta1
kind: APPolicy
metadata:
  name: my-ap-policy
  namespace: default
spec:
  policy:
    applicationLanguage: utf-8
    blocking-settings:
      violations:
      - alarm: false
        block: true
        name: VIOL_DATA_GUARD
      - alarm: false
        block: false
        name: VIOL_PARAMETER_VALUE_METACHAR
    bot-defense:
      mitigations:
        classes:
        - action: alarm
          name: trusted-bot
        - action: alarm
          name: untrusted-bot
        - action: block
          name: malicious-bot
      settings:
        isEnabled: true
    data-guard:
      creditCardNumbers: true
      enabled: true
      enforcementMode: ignore-urls-in-list
      enforcementUrls: []
      lastCcnDigitsToExpose: 4
      lastSsnDigitsToExpose: 4
      maskData: true
      usSocialSecurityNumbers: true
    enforcementMode: transparent
    name: my-ap-policy
    server-technologies:
    - serverTechnologyName: Unix/Linux
    - serverTechnologyName: Nginx
    - serverTechnologyName: Apache/NCSA HTTP Server
    - serverTechnologyName: PHP
    - serverTechnologyName: JavaScript
    - serverTechnologyName: PostgreSQL
    template:
      name: POLICY_TEMPLATE_NGINX_BASE
