{
 "title": "NAP - Attack Signatures",
 "description": "This Dashboard provides more visibility into the logs generated by NGINX App Protect. This is part of a series of NGINX App Protect Dashboards",
 "tags": [
  "nginx",
  "nap"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "context",
    "label": "Context",
    "query": "{\"find\": \"terms\", \"field\": \"violations.context.keyword\", \"size\": 10}"
   },
   {
    "name": "vsname",
    "label": "virtualServerName",
    "query": "{\"find\": \"terms\", \"field\": \"virtualServerName.keyword\", \"size\": 1000}"
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": "{\"find\": \"terms\", \"field\": \"requestPolicy.fullPath.keyword\", \"size\": 500}"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "{\"find\": \"terms\", \"field\": \"host.keyword\", \"size\": 1000}"
   },
   {
    "name": "accuracy",
    "label": "Accuracy",
    "query": "{\"find\": \"terms\", \"field\": \"violations.signature.accuracy.keyword\", \"size\": 5}"
   },
   {
    "name": "risk",
    "label": "Risk",
    "query": "{\"find\": \"terms\", \"field\": \"violations.signature.risk.keyword\", \"size\": 5}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Blocked",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "requestStatus.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Signatures Risk",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.signature.risk.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Signatures Accuracy",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.signature.accuracy.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CVEs",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.signature.references.value.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Blocking Settings",
     "type": "table",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.enforcementState.isBlocked",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Countries",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "country_name.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Bots",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "client_class.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Methods",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "method.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Signature Hits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Attackers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clientIp",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "clientIp",
       "id": "1",
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top 20 Signature Hits over Time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 15, "x": 9, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.signature.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "20" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "3", "type": "count" }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Signatures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.signature.signatureId",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "violations.signature.signatureId",
       "id": "1",
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Context",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.context.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "15" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      {
       "field": "violations.signature.signatureId",
       "id": "3",
       "type": "cardinality"
      }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clientIp",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "url-decode.keyword", "id": "3", "type": "cardinality" },
      {
       "field": "violations.signature.signatureId",
       "id": "4",
       "type": "cardinality"
      },
      { "field": "requestPolicy.fullPath.keyword", "id": "5", "type": "cardinality" }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Virtual Servers",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "virtualServerName.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      {
       "field": "violations.signature.signatureId",
       "id": "3",
       "type": "cardinality"
      },
      { "field": "clientIp.keyword", "id": "4", "type": "cardinality" }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "requestPolicy.fullPath.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      {
       "field": "violations.signature.signatureId",
       "id": "3",
       "type": "cardinality"
      },
      { "field": "clientIp.keyword", "id": "4", "type": "cardinality" }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "table",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "url-decode.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "500" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      {
       "field": "violations.signature.signatureId",
       "id": "4",
       "type": "cardinality"
      }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Signature Names",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.signature.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
       "type": "terms"
      },
      {
       "field": "violations.signature.signatureId",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "violations.signature.accuracy.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "violations.signature.risk.keyword",
       "id": "8",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "violations.signature.references.value.keyword",
       "id": "9",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "_term",
        "size": "10"
       },
       "type": "terms"
      },
      {
       "field": "violations.enforcementState.isBlocked",
       "id": "10",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "clientIp", "id": "3", "type": "cardinality" }
     ],
     "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Parameter / Header / Cookie Context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Entity Names",
     "type": "table",
     "gridPos": { "h": 12, "w": 17, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.observedEntity.name-decode.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        },
        {
         "field": "violations.observedEntity.value-decode.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
         "type": "terms"
        },
        {
         "field": "violations.context.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "clientIp", "id": "3", "type": "cardinality" },
        {
         "field": "violations.signature.signatureId",
         "id": "4",
         "type": "cardinality"
        }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && (violations.context.keyword:parameters || violations.context.keyword:headers || violations.context.keyword:cookies) && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Entity Values",
     "type": "table",
     "gridPos": { "h": 12, "w": 7, "x": 17, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.observedEntity.value-decode.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1000" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "requestPolicy.fullPath.keyword", "id": "5", "type": "cardinality" },
        {
         "field": "violations.observedEntity.name.keyword",
         "id": "7",
         "type": "cardinality"
        }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && (violations.context.keyword:parameters || violations.context.keyword:headers || violations.context.keyword:cookies) && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Parameter / Header / Cookie violation details",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "1000" }, "type": "logs" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && (violations.context.keyword:parameters || violations.context.keyword:headers || violations.context.keyword:cookies) && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "URL Context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "URLs Violations",
     "type": "table",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.snippet.buffer-decode.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "clientIp", "id": "3", "type": "cardinality" },
        {
         "field": "violations.signature.signatureId",
         "id": "5",
         "type": "cardinality"
        }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.context.keyword:urls && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "URL violation logs",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "1000" }, "type": "logs" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.context.keyword:urls && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Violations",
     "type": "table",
     "gridPos": { "h": 12, "w": 19, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "violations.snippet.buffer-decode.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "100" },
         "type": "terms"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" },
        { "field": "clientIp", "id": "3", "type": "cardinality" },
        { "field": "url-decode.keyword", "id": "4", "type": "cardinality" },
        { "field": "requestPolicy.fullPath.keyword", "id": "5", "type": "cardinality" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.context.keyword:request && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Request violation logs",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "1000" }, "type": "logs" }
       ],
       "query": "violations.context.keyword:$context && virtualServerName.keyword:$vsname && requestPolicy.fullPath.keyword:$policy && host.keyword:$device && violations.signature.risk.keyword:$risk && violations.signature.accuracy.keyword:$accuracy && violations.context.keyword:request && violations.violation.name.keyword:VIOL_ATTACK_SIGNATURE",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}